name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-macos:
    name: ${{ matrix.subcommand }} with Xcode ${{ matrix.xcode }} on macOS
    runs-on: macos-12
    strategy:
      matrix:
        xcode: ["13.3.1", "13.4", "13.4.1"]
        subcommand: ["Build", "Test"]
    steps:
    - uses: actions/checkout@v3
    - name: ${{ matrix.subcommand }}
      run: |
        xcodebuild -version
        swift --version
        swift package --version
        subcommand=`echo ${{ matrix.subcommand }} | tr '[:upper:]' '[:lower:]'`
        swift $subcommand -v
      env:
        DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app

  run-ubuntu:
    name: Build and Test with Swift ${{ matrix.swift }} on Ubuntu
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    strategy:
      matrix:
        swift: ["5.6.0", "5.6.1", "5.6.2"]
    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: |
        swift --version
        swift package --version
        swift test -v
